apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: vote-ui-git
spec:
  url: https://github.com/viyancs/pipelines-vote-ui.git
  ref: master
  frequency: 1m
  type: github # can also be gitlab
  pipelineRef:
    name: build-and-deploy
    params:
    - name: git-url
      expression: "'https://github.com/viyancs/pipelines-vote-ui.git'"
    - name: git-revision
      expression: commit.sha
    - name: deployment-name
      expression: "'pipelines-vote-ui'"
    - name: IMAGE
      expression: "'image-registry.openshift-image-registry.svc:5000/pipeline-tutorial/pipelines-vote-ui'"
    workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: thin
            resources:
              requests:
                storage: 500Mi
        