apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vote-app-storage-claim
  namespace: pipeline-tutorial
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
